services:
  - type: web
    name: order-management-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@postgres:5432/postgres

databases:
  - name: postgres
    databaseName: postgres
    user: postgres
    plan: free 